package certsdb

import (
	"ksef/internal/logging"
	"ksef/internal/runtime"
	"slices"
	"time"
)

func isPreferred(cert Certificate, preferredCertProfile string) bool {
	return cert.ProfileName == preferredCertProfile || cert.UID == preferredCertProfile || cert.SerialNumber == preferredCertProfile
}

func (cdb *CertificatesDB) GetByUsage(usage Usage, nip string) (Certificate, error) {
	foundCerts := cdb.FetchByUsage(usage, nip)
	// for Authentication there are two possible choices - self-signed and ksef-issued.
	// let's sort the list in that order and try to use ksef-issued (if it hasn't expired yet)
	// and the self-signed (if it exists)

	if foundCerts != nil {
		preferredCertProfile := runtime.GetPreferredCertProfile(cdb.vip)

		slices.SortFunc(foundCerts, func(a, b Certificate) int {
			// if there is a preferred certificate ID, we should always make it so that
			// it ends up at the top of the slice
			if preferredCertProfile != "" {
				if isPreferred(a, preferredCertProfile) {
					return -1
				} else if isPreferred(b, preferredCertProfile) {
					return 1
				}
			} else {
				if a.SelfSigned && !b.SelfSigned {
					return 1
				} else if !a.SelfSigned && b.SelfSigned {
					return -1
				}
			}
			return 0
		})

		logging.CertsDBLogger.Debug("wybrano certyfikat", "id", foundCerts[0].UID, "typ", foundCerts[0].Usage, "self-signed", foundCerts[0].SelfSigned)

		return foundCerts[0], nil
	}

	return Certificate{}, ErrCertificateNotFound
}

func (cdb *CertificatesDB) FetchByUsage(usage Usage, nip string) (foundCerts []Certificate) {
	now := time.Now()

	for _, cert := range cdb.certs {
		if !slices.Contains(cert.Usage, usage) || !cert.available {
			continue
		}
		if cert.ValidFrom.After(now) || cert.ValidTo.Before(now) {
			logging.CertsDBLogger.Debug("certyfikat poza zakresem ważności", "id", cert.UID)
			continue
		}
		// self-signed certificates do not need to have a NIP. they can - if they're
		// generated by NIP rather than by PESEL
		if nip != "" && cert.NIP != nip && !cert.SelfSigned {
			logging.CertsDBLogger.Debug("certyfikat wystawiony dla innego numeru NIP", "id", cert.UID)
			continue
		}

		foundCerts = append(foundCerts, *cert)
	}

	return foundCerts
}
