baseURL = 'https://ksef.po-godzinach.info/'
languageCode = 'pl-pl'
title = 'klient KSeF'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

[params.docs]
    darkMode = true