on:
  release:
    types: [created, edited]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        pre_command: export GODEBUG=http2client=0
        goversion: "https://dl.google.com/go/go1.21.0.linux-amd64.tar.gz"
        project_path: "./cmd/ksef"
        binary_name: "ksef"
